name: Hexlet CI App Workflow # Название вашего воркфлоу

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies and build project (make setup)
        run: make setup
      - name: Run linters (make lint)
        run: make lint
      - name: Run tests (make test)
        run: make test
